"""
Package utilities and configuration.
"""

from pkg.config import get_settings
from pkg.errors import (
    AppError,
    MarketClientError,
    ConfigurationError,
    AuthenticationError,
    RateLimitError,
    OrderError,
    InsufficientBalanceError,
    InvalidOrderError,
    OrderExecutionError,
    SettlementError,
    PortfolioError,
    BalanceError,
    PositionError,
    NotificationError,
    DiscordError,
    EmailError,
    NotificationRateLimitError,
    StrategyError,
    NoOpportunityError,
    MarketFilterError,
    DashboardError,
    DashboardRouteError,
    DashboardConfigError,
    SystemError,
    DatabaseError,
    InitializationError,
    get_error_message,
    get_error_details,
)

__all__ = [
    "get_settings",
    # Errors
    "AppError",
    "MarketClientError",
    "ConfigurationError",
    "AuthenticationError",
    "RateLimitError",
    "OrderError",
    "InsufficientBalanceError",
    "InvalidOrderError",
    "OrderExecutionError",
    "SettlementError",
    "PortfolioError",
    "BalanceError",
    "PositionError",
    "NotificationError",
    "DiscordError",
    "EmailError",
    "NotificationRateLimitError",
    "StrategyError",
    "NoOpportunityError",
    "MarketFilterError",
    "DashboardError",
    "DashboardRouteError",
    "DashboardConfigError",
    "SystemError",
    "DatabaseError",
    "InitializationError",
    "get_error_message",
    "get_error_details",
]
